import 'package:portfolio/core/constants/constant.dart';

const String kProfile = '${image}profile.png';
const String kBluecollerio = '${image}bluecollerio.png';
const String kEnstva = '${image}enstva.png';
const String kEventally = '${image}eventally.png';
const String kDAlert = '${image}d_alert.png';
const String kKerala = '${image}kerala.png';
const String kHeart = '${svg}heart.svg';
const String kLightMode = '${svg}light_mode.svg';
const String kDarkMode = '${svg}dark_mode.svg';
const String kHi = '${svg}hi.svg';
const String kFlutter = '${svg}flutter.svg';
const String kDart = '${svg}dart.svg';
const String kPython = '${svg}python.svg';
const String kSql = '${svg}sql.svg';
const String kFirebase = '${svg}firebase.svg';
const String kGit = '${svg}git.svg';
const String kGithub = '${svg}github.svg';
const String kPostman = '${svg}postman.svg';
const String kMenu = '${svg}menu.svg';
const String kShare = '${svg}share.svg';
const String kDownload = '${svg}download.svg';
const String kCsharp = '${svg}csharp.svg';